### ISSUE TITLE
Dev problem

### ISSUE THREAD

**Issue by Liangtaiwan** [DRCSolutionService/DRCD#1]
The dev set answers are duplicate in the same question.
Also, in SQuAD dataset, it has 3 different answers in dev set and test set, so the human performance is much higher than your dataset in EM performance. Are you going to provide more answer?

**Comment by DRCKnowledgeTeam** [comment]
1. In dev set, each of the question contains 2 answers provided by different annotators. It is possible that they have the same answer. 
2. We have only 2 different answers in dev and test set. For now, we don't have a plan to add more answer.
