### ISSUE TITLE
Format conversion to SQuAD2.0

### ISSUE THREAD

**Issue by allenyummy** [DRCSolutionService/DRCD#4]
When you used Bert-Chinese model to do the DRCD tasks like your paper told us, is there anything such as format conversion that we need to do first, and then we can use Bert-Chinese model to do DRCD tasks ?

p.s. Format conversion means that convert DRCD format to SQuAD2.0 format.

**Comment by DRCKnowledgeTeam** [comment]
there is no SQuAD2.0 version of DRCD
all the result presented in the paper are processed under SQuAD1.1 format 

if you want to convert the format into SQuAD2.0 version
you need to form non-answer question

@chiangyulun0914 
if any other questions please let me know
