### ISSUE TITLE
想问一下怎么样才能获取全部的数据集呢

### ISSUE THREAD

**Issue by ECNUHP** [DRCSolutionService/DRCD#5]
是要发邮件来申请全部的数据集嘛？

**Comment by DRCKnowledgeTeam** [comment]
@ECNUHP 目前github上已是公開全部的數據集包含training set, dev set, test set
網頁上簡單介紹數據集的基本資訊，arXiv paper當中有對數據集內容較多的說明。

**Comment by ECNUHP** [comment]
> @ECNUHP 目前github上已是公開全部的數據集包含training set, dev set, test set
> 網頁上簡單介紹數據集的基本資訊，arXiv paper當中有對數據集內容較多的說明。

哦哦，好的，很感谢您的回复
